// Type definitions for graphql-relay 0.6
// Project: https://github.com/neo4j-graphql/neo4j-graphql-js
// Definitions by: Arvitaly <https://github.com/nopzen>
// Definitions: https://github.com/DefinitelyTyped/neo4j-graphql-js
// TypeScript Version: 3.8

import { GraphQLSchema, GraphQLFieldResolver } from 'graphql';

declare module 'neo4j-graphql-js' {
    export function makeAugmentSchema(): GraphQLSchema;
    export function neo4jgraphql(): any;
    export function augmentSchema(): any;
    export function cypherQuery(): any;
    export function cypherMutation(): any;
    export function inferSchema(): any;
}

/**
 * AugmentSchemaResolvers
 * @remarks is an optional argument (empty object by default) and should be an object or an array of objects that follow the pattern explained in {@link https://www.graphql-tools.com/docs/resolvers/|article on resolvers}
 */

type AugmentSchemaResolvers = {
    [key: string]: GraphQLFieldResolver<any, any, { [argName: string]: any }>;
};

/**
 * AugmentSchemaLogger
 * @remarks logger is an optional argument, which can be used to print errors to the server console that are usually swallowed by GraphQL. The logger argument should be an object with a log function, eg. `const logger = { log: e => console.log(e) }`
 */

type AugmentSchemaLogger = {
    log: (msg: string) => void;
};

/**
 * AugmentSchemaAuthConfig
 * @param isAuthenticated   enables `@isAuthenticated` directive, **Optional, defaults to true**
 * @param hasRole           enables `@hasRole` directive, **Optional, defaults to true**
 * @param hasScope          enables `@hasScope` directive, **Optional, defaults to true**
 */
type AugmentSchemaAuthConfig = {
    isAuthenticated?: boolean;
    hasRole?: boolean;
    hasScope?: boolean;
};

/**
 * AugmentSchemaConfig
 *
 * @param query     Configure the autogenerated Query fields. Can be enabled/disabled for all types or a list of individual types to exclude can be passed. Commonly used to exclude payload types. **Optional defaults to `true`**
 * @param mutation  Configure the autogenerated Mutation fields. Can be enabled/disabled for all types or a list of individual types to exclude can be passed. Commonly used to exclude payload types. **Optional, defaults to `true`**
 * @param debug     Enable/disable logging of generated Cypher queries and parameters. **Optional, defaults to `true`**
 * @param auth      Used to enable authorization schema directives (@isAuthenticated, @hasRole, @hasScope). If enabled, directives from the graphql-auth-directives are declared and can be used in the schema. If @hasScope is enabled it is automatically added to all generated query and mutation fields. See the authorization guide for more information. **Optional, defaults to `false`**
 */
type AugmentSchemaConfig = {
    query?: boolean | { exclude: string[] };
    mutation?: boolean | { exclude: string[] };
    debug?: boolean;
    auth?: boolean | AugmentSchemaAuthConfig;
};

type MakeAugmentSchemaOptions = {
    schema?: GraphQLSchema;
    typeDefs: string;
    resolvers?: AugmentSchemaResolvers;
    logger?: AugmentSchemaLogger;
    config?: AugmentSchemaConfig;
};
